### ISSUE TITLE
Make pulling from registry configurable for inside-build

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#126]
Currently there is no option to disable pulling from registry the base image. In our case this will re-tag the images with older versions which is not what we want.

**Comment by TomasTomecek** [comment]
Does it mean, that images are already present in your environment and pulling base image according to dockerfile just messes everything up?

Looking at code, I can see your point now. I've changed the flow a bit to pull base images *always* before running pre-build plugins, because one pre-build plugin requires to have the base image already present on system.

How serious is this? When do you expect to provide a resolution?
I think it's time to make pulling base image a plugin.

**Comment by goldmann** [comment]
That's correct - our images which are available on the CI host - are **newer** than on the registry, because we don't push every time (it does not make sense to waste so much space). We push our images only when we think it makes sense.

Your change to pull always almost messed our release today, because I barely catch that we still use 2 weeks old images instead newly built... I accidentally found the issue when I did not see two tags for the new image.

We use a patched ([commented out this](https://github.com/DBuildService/dock/blob/master/dock/inner.py#L200-201)) version of Dock. We don't need anything to be fixed ASAP for us, but this needs to be an option and I consider this as a bug from my POV.

**Comment by jpopelka** [comment]
> I think it's time to make pulling base image a plugin.

From architectural point of view it looks like a good candidate for a pre-build plugin, yes.
But I think most common use-case is to pull a base image before build so if we make it a plugin, most build jsons will need to include it.
I mean, we can't make a plugin to **not** pull image, right ?
If we agree that more common is to pull base image, then I'd vote for making this a DockerBuildWorkflow option (called let's say *dont_pull_base_image*) so one would need to specify it in build json **only** if the pulling is unwanted.

**Comment by TomasTomecek** [comment]
> But I think most common use-case is to pull a base image before build so if we make it a plugin, most build jsons will need to include it.

You can build image without pulling base image explicitly because docker has option for that in API:

https://github.com/docker/docker-py/blob/396af7adbe480787ac9cb2ba866d6d2125b8dd30/docker/client.py#L307

The reason we are not using that is that you cannot specify source registry. docker wants to pull everything from docker hub. That's pretty bad because I assume that most of our users use custom registries, hence the custom pull function.

> I mean, we can't make a plugin to not pull image, right ?

Well, we should provide a way to configure `pull` argument of docker-py's `build` method

> If we agree that more common is to pull base image, then I'd vote for making this a DockerBuildWorkflow option (called let's say dont_pull_base_image) so one would need to specify it in build json only if the pulling is unwanted.

In the end, I don't care much if it's going to be plugin or not. If you feel like that keeping architecture as it is now is better, let's do it that way.

**Comment by jpopelka** [comment]
> Well, we should provide a way to configure pull argument of docker-py's build method

AFAICT we don't have a use-case so far, so I'd keep it simple and hardwire it to False for now.

> In the end, I don't care much if it's going to be plugin or not. If you feel like that keeping architecture as it is now is better, let's do it that way.

IMHO plugin would make sense if default was to **not** pulling.

**Comment by TomasTomecek** [comment]
> AFAICT we don't have a use-case so far, so I'd keep it simple and hardwire it to False for now.

Fair enough.

There's already a dock issue for managing arguments of build method; will rewrite it a bit.
