### ISSUE TITLE
tag by labels: if n-v-r labels miss in dockerfile, don't tag!

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#145]
because we retag base image

**Comment by jpopelka** [comment]
I've tried to look at this, but need some clarification.

So the `TagByLabelsPlugin` takes n-v-r labels from built image and adds them to `workflow.tag_conf`, which is later used by `TagAndPushPlugin` for the tagging itself.

If there are no n-v-r labels in Dockerfile, they are not added into the built image and `TagByLabelsPlugin` fails with `RuntimeError` so no tagging happens actually.

What am I missing ?

**Comment by TomasTomecek** [comment]
The should be done even before build. Workflow:

1. clone repo
2. parse dockerfile
3. get all labels
4. if some of N-V-R labels miss
  - abort
5. else
  - continue

**Comment by jpopelka** [comment]
So it means it won't be possible to build from Dockerfile which doesn't contain N-V-R ? Then you should probably add N-V-R into your https://github.com/TomasTomecek/docker-hello-world.git , because it's mentioned in README.md

Also I still don't understand why we actually want this. I'm missing the point about retagging base image.

**Comment by jpopelka** [comment]
So as I understand what Tomas told me ;-) we need this because:
When we have base image with N-V-R labels and we build layered image from a Dockerfile without N-V-R labels, the new built image will somehow inherit the N-V-R labels from the base image, which is not what we want.

I've implemented the labels checking as a new pre-build plugin.

**Comment by TomasTomecek** [comment]
Ready to merge from my PoV.
