### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#56]
The current name of the project is very bad. In most cases when you talk about it you need to explain if you are talking about Dock indeed or Docker but you just typed it wrongly. It is very confusing to use such similar name.

**Comment by TomasTomecek** [comment]
What would you suggest then? The name is inspired after [mock](http://fedoraproject.org/wiki/Projects/Mock) project.

**Comment by goldmann** [comment]
Dunno, maybe just `dbs`? Even shorter and you already own the organization on GitHub.

**Comment by l-d-j** [comment]
+1 for dbs for me :) its nicer

**Comment by TomasTomecek** [comment]
TBH, we are planning to move dock and osbs under project atomic and deprecate this org. (CC @vpavlin )

**Comment by goldmann** [comment]
I guess that's not a blocker for a rename to `dbs` :)

**Comment by TomasTomecek** [comment]
Okay, it looks like we'll move this project under project atomic org and we'll also rename it. Setting high prio then.

**Comment by TomasTomecek** [comment]
Thought thoroughly about this and picked name "reactor" (suggested by @vpavlin). Expect rename soon and following move under project atomic.

**Comment by bkabrda** [comment]
So, my proposal for this would be:
- Rename project to "atomic-reactor" (github repo, name in `setup.py` and in docs).
- The Python module should be called `atomic_reactor`. I know it's kinda lengthy, but there's already a `reactor` project on PyPI which has `reactor` module, and it's a good habit to have module name same as project name, except `s/-/_/`.
- As far as the executable name goes, I think we could have either `reactor` or `atomic-reactor`. `reactor` is good since it's short; `atomic-reactor` is better for consistency and discoverability - if I install module `atomic-reactor`, the name is also my first guess when trying to figure out executable name. So I'd go with `atomic-reactor` for name as well.

Comments are welcome!

**Comment by twaugh** [comment]
ISTR the original rationale for renaming `dock` was to prevent tab-completion conflicts with `docker`. If we rename it to `atomic-reactor`, aren't we going to have the same issue with `atomic`?

**Comment by bkabrda** [comment]
@twaugh well, so we can rename the executable to `reactor` and leave the rest as I proposed. BTW there's already `atomic` and `atomicapp`, so the tab completion issue is likely to happen for atomic* stuff users even if we choose to name our executable just `reactor`.

**Comment by twaugh** [comment]
Hm, that's true.

**Comment by TomasTomecek** [comment]
Well, first thing I'll do will be:
```
alias r="[atomic-]reactor"
```

I'm fine with naming it `atomic-reactor` and naming module `atomic_reactor`. Regarding executable, I prefer `reactor`, but no strong feelings.
